#ifndef CONSTDEFINE_H
#define CONSTDEFINE_H

#define INI_FILE_FULL_NAME "set.ini"

#define CREATE_USER_DB "CREATE "
#define CREATE_COMPANY_DB "CREATE "
#define CREATE_OSTAT_RDB "CREATE "
#define CREATE_CONTRACT "CREATE "


#define CREATE_SETINGS_RDB ""
#define CREATE_BANKS_INDEX_DB ""
#define CREATE_CONTRACT_TYPE_DB ""

#endif // CONSTDEFINE_H
